# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LookARound' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookARound
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  # pod 'FacebookCore'  ## Waiting until FB pushes Swift 4 fix
  # pod 'FacebookLogin' ## Waiting until FB pushes Swift 4 fix
  # pod 'Mapbox-iOS-SDK', '~> 3.6'
  # pod 'FLEX', '~> 2.0', :configurations => ['Debug']

end
